CREATE DATABASE school

CREATE TABLE IF NOT EXISTS `People` (
	`PersonID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`FullName`	TEXT NOT NULL,
	`DateOfBirth`	TEXT NOT NULL,
	`ScreenName`	TEXT NOT NULL,
	`IsAdult`	INTEGER NOT NULL
);